version: "3"
#services section includes all the services included in it.
services:

  configuration-server:
    build: configuration-server
    ports:
      - 8085:8085
    restart: always

  eurekaa-server:
    build: eurekaa-server/
    container_name: eurekaa-server
    ports:
      - 9099:9099
    restart: always
    network_mode: host

  trackservice:
    build: trackservice/
    ports:
      - 8084:8084
    depends_on:
      - eurekaa-server
      - configuration-server
    restart: always
    network_mode: host

  api-gateway:
    build: api-gateway/
    ports:
      - 8081:8081
    depends_on:
      - trackservice
    restart: always

  user-services:
    build: user-services/
    ports:
      - 8087:8087
    restart: always